# title: Software, Math and Physics
# description: Michael Lubinsky
# theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  parse_block_html: true
  auto_links: true
